### ISSUE TITLE
Too old

### ISSUE THREAD

**Issue by tyduptyler13** [schwern/alien-svn#3]
Needs to be updated to support the latest Ruby and Berkeley DB.

It also seems to be using deprecated functions in SVN.

**Comment by schwern** [comment]
We plan to upgrade to the latest 1.7.x shortly and eventually to the 1.8.x branch.  Beyond that, we're beholden to whatever SVN does.  [You'll have to talk to them](https://subversion.apache.org/reporting-issues.html).
